models:
  llm:
    model: ai/deepseek-r1-distill-llama

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    models:
      llm:
        endpoint_var: LLM_URL
        model_var: LLM_NAME

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
