version: '3.8'

services:
  api:
    build:
      context: ../api
    volumes:
      - ../api:/app
    ports:
      - 8000:8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ../frontend
    volumes:
      - ../frontend:/app
    ports:
      - 8501:8501
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
